apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webtest
  name: webtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webtest
  strategy: {}
  template:
    metadata:
      labels:
        app: webtest
    spec:
      nodeSelector:
        node-role.kubernetes.io/app: ""
      containers:
        - image: ghcr.io/cloudnative-pg/webtest:1.6.0
          name: webtest
          env:
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-eu-app
                  key: password
            - name: USER
              valueFrom:
                secretKeyRef:
                  name: pg-eu-app
                  key: username
            - name: DATABASE_URL
              value: "postgres://$(USER):$(PASSWORD)@pg-eu-rw/app?sslmode=require&connect_timeout=2"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: webtest
  name: webtest
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: webtest
  type: ClusterIP

