apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-eu
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:17-minimal-bookworm

  storage:
    size: 1Gi

  # See https://cloudnative-pg.io/documentation/current/storage/#volume-for-wal
  walStorage:
    size: 1Gi

  # See https://cloudnative-pg.io/documentation/current/scheduling/#isolating-postgresql-workloads
  affinity:
    nodeSelector:
      node-role.kubernetes.io/postgres: ""
    tolerations:
    - key: node-role.kubernetes.io/postgres
      operator: Exists
      effect: NoSchedule
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
    podAntiAffinityType: required

  # See https://cloudnative-pg.io/documentation/current/bootstrap/#bootstrap-an-empty-cluster-initdb
  bootstrap:
    initdb:
      dataChecksums: true

  postgresql:
    # See https://cloudnative-pg.io/documentation/current/postgresql_conf/#the-postgresql-section
    parameters:
      # Some very basic Postgres settings
      max_connections: '100'
      log_checkpoints: 'on'
      log_lock_waits: 'on'
      pg_stat_statements.max: '10000'
      pg_stat_statements.track: 'all'
      hot_standby_feedback: 'on'
      # Container images work fine with sysv shared memory
      shared_memory_type: 'sysv'
      dynamic_shared_memory_type: 'sysv'

  plugins:
  - name: barman-cloud.cloudnative-pg.io
    isWALArchiver: true
    parameters:
      barmanObjectName: minio-eu
      serverName: pg-eu

  # See https://cloudnative-pg.io/documentation/current/replica_cluster/#distributed-topology
  replica:
    self: pg-eu
    primary: pg-eu
    source: pg-us

  externalClusters:
  - name: pg-eu
    plugin:
      name: barman-cloud.cloudnative-pg.io
      parameters:
        barmanObjectName: minio-eu
        serverName: pg-eu
  - name: pg-us
    plugin:
      name: barman-cloud.cloudnative-pg.io
      parameters:
        barmanObjectName: minio-us
        serverName: pg-us
---
# See https://cloudnative-pg.io/documentation/current/backup/#scheduled-backups
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: pg-eu-backup
spec:
  method: plugin
  schedule: '0 0 0 * * *'
  backupOwnerReference: self
  cluster:
    name: pg-eu
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
  immediate: true
