apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-eu
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:18-system-trixie

  storage:
    size: 1Gi

  # See https://cloudnative-pg.io/documentation/current/storage/#volume-for-wal
  walStorage:
    size: 1Gi

  # See https://cloudnative-pg.io/documentation/current/scheduling/#isolating-postgresql-workloads
  affinity:
    nodeSelector:
      node-role.kubernetes.io/postgres: ""
    tolerations:
    - key: node-role.kubernetes.io/postgres
      operator: Exists
      effect: NoSchedule
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
    podAntiAffinityType: required

  # See https://cloudnative-pg.io/documentation/current/bootstrap/#bootstrap-an-empty-cluster-initdb
  bootstrap:
    initdb:
      dataChecksums: true

  postgresql:
    # See https://cloudnative-pg.io/documentation/current/postgresql_conf/#the-postgresql-section
    parameters:
      # Some very basic Postgres settings
      max_connections: '100'
      log_checkpoints: 'on'
      log_lock_waits: 'on'
      pg_stat_statements.max: '10000'
      pg_stat_statements.track: 'all'
      hot_standby_feedback: 'on'
      # Container images work fine with sysv shared memory
      shared_memory_type: 'sysv'
      dynamic_shared_memory_type: 'sysv'

  backup:
    barmanObjectStore:
      destinationPath: s3://backups/
      endpointURL: http://minio-eu:9000
      s3Credentials:
        accessKeyId:
          name: minio-eu
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: minio-eu
          key: ACCESS_SECRET_KEY
      wal:
        compression: gzip

  # See https://cloudnative-pg.io/documentation/current/replica_cluster/#distributed-topology
  replica:
    self: pg-eu
    primary: pg-eu
    source: pg-us

  externalClusters:
  - name: pg-eu
    barmanObjectStore:
      serverName: pg-eu
      destinationPath: s3://backups/
      endpointURL: http://minio-eu:9000
      s3Credentials:
        accessKeyId:
          name: minio-eu
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: minio-eu
          key: ACCESS_SECRET_KEY
      wal:
        compression: gzip
  - name: pg-us
    barmanObjectStore:
      serverName: pg-us
      destinationPath: s3://backups/
      endpointURL: http://minio-us:9000
      s3Credentials:
        accessKeyId:
          name: minio-us
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: minio-us
          key: ACCESS_SECRET_KEY
      wal:
        compression: gzip
---
# See https://cloudnative-pg.io/documentation/current/backup/#scheduled-backups
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: pg-eu-backup
spec:
  schedule: '0 0 0 * * *'
  backupOwnerReference: self
  cluster:
    name: pg-eu
  immediate: true
